# Generated by Django 4.2 on 2023-04-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
